config/routes.rb
Rails.application.routes.draw do

  root controller: 'comps', action: 'index'

  resources :comps do
    member do
      get 'join'
      get 'leaders'
    end
  end

  resources :climbers do
    collection do
      put 'login'
      get 'signin'
      put 'logout'
    end
  end

  resources :routes do
    member do
      put 'sendClimb'
      put 'attemptClimb'
      put 'witnessClimb'
    end
  end

  resources :colleges

  get 'scoresheet' => 'scoresheets#index'
  put 'scoresheet/speed' => 'scoresheets#speed'
  get 'scoresheet/climbs' => 'scoresheets#climbs'
  get 'scoresheet/submit' => 'scoresheets#submit'
  get 'scoresheet/scores' => 'scoresheets#scores'

end

app/models/comp.rb
class Comp < ActiveRecord::Base
  has_many :routes
  has_many :scoresheets
  has_many :climbers, through: :scoresheets

  validates :location, presence: true
  validates :date, presence: true
  validates :state, presence: true

  enum state: [:closed, :open, :running]

  def join(climber_id)
    # Currently logged in climber
    # joins comp and creates new scoresheet
    return nil if climber_id.nil?
    sc = Scoresheet.where({climber_id: climber_id, comp_id: self.id}).first
    return sc if sc.present?
    return Scoresheet.create({
      comp_id: self.id,
      climber_id: climber_id,
      boulder_score: 0,
      sport_score: 0,
    })
  end

  def leaders
    # Get the leaders!
    males = self.scoresheets.joins(climber: :college).where(climbers: {gender: 0}).select("scoresheets.*, climbers.*, colleges.name AS college_name")
    females = self.scoresheets.joins(climber: :college).where(climbers: {gender: 1}).select("scoresheets.*, climbers.*, colleges.name AS college_name")
    results = {
      males: {
        boulder: males.boulder_leaders,
        sport: males.sport_leaders,
        speed: males.speed_leaders
      },
      females: {
        boulder: females.boulder_leaders,
        sport: females.sport_leaders,
        speed: females.speed_leaders
      }
    }
    results
  end
end

app/controllers/comps_controller.rb
class CompsController < ApplicationController

  before_action :find_comp, except: [:index, :new, :create]

  def index
    # Homepage
    # If climber logged in with
    # active scoresheet,
    # redirect to scoresheet home
    if @current_scoresheet.present?
      redirect_to scoresheet_path
    end
    @comps = Comp.where("state = ? OR state = ?", 1, 2)
    @upcoming = Comp.closed.where("date >= ?", Date.today)
    @recent = Comp.closed.where("date < ?", Date.today)
  end

  def show
    # this is where we see who are the top 3 in
    # each category
  end

  def edit 
    @routes = @comp.routes.order(discipline: :asc, points: :desc)
  end

  def leaders
    render json: @comp.leaders
  end

  def new
    @comp = Comp.new
  end

  def create
    @comp = Comp.new(comp_params)
    if @comp.save
      redirect_to @comp
    else
      render 'new'
    end
  end

  def update
    @comp = @comp.update(comp_params)
    if @comp
    else
    end
  end

  def destroy
  end

  def start
    @comp.state = 'running'
    render json: @comp
  end
  
  def open
    @comp.state = 'open'
    render json: @comp
  end

  def close
    @comp.state = 'closed'
    render json: @comp
  end

  def join
    if current_climber.nil?
     # render_error(500, "Climber not logged in")
      redirect_to signin_climbers_path(comp: @comp.id)
      return
    end

    if (@comp.state == 'closed')
      render_error(500, "Comp not open")
      return
    end

    scoresheet = @comp.join(current_climber.id)
    session[:scoresheet] = scoresheet.id
    redirect_to '/scoresheet'
  end

  private

  def find_comp
    @comp = Comp.find(params[:id])
  end

  def comp_params
    params.require(:comp).permit(:id, :state, :location, :date)
  end

end

app/helpers/comp_helper.rb
module CompHelper
end

app/views/comps/_compcard.html.erb
<ul>
<% comps.each do |c| %>
<a href = "<%= join_comp_path(c) %>" class='block-link'>
    <div class='comp-card'>
      <li><%= c.location.upcase %></li>
      <li><%= c.date %></li>
    </div>
  </a>
<% end %>
  </ul>

app/views/comps/_form.html.erb
<%= form_for @comp do |f| %>
  <%= render partial: 'layouts/errors', locals: {obj: @comp} %>

  <h4>
    LOCATION
  </h4>

  <%= f.text_field(:location, class: 'input-large', value: @comp.location) %>

  <h4>
    DATE
  </h4>

  <%= f.date_field(:date, class: 'input-large datepicker', value: @comp.date) %>
  <h4>
    STATUS
  </h4>

  <%= f.select(:state, [['Closed', :closed], ['Open', :open]], {}, {class: 'select-large'}) %>
  
  <br />
  <br />

  

  <%= f.submit("SUBMIT", class: 'block-link') %>

<% end %>

app/views/comps/edit.html.erb
<% # editing comps %>

<h2>
  EDIT COMP
</h2>

<%= render partial: 'form' %>
<ul>
  <% @routes.each do |route| %>
    <%= form_for :route, url: route_path(route), method: :patch do |f| %>
      <%= f.text_field :name, value: route.name %>
      <%= f.number_field :points, value: route.points %>
      <%= f.text_field :color, value: route.color %>
      <%= f.text_field :grade, value: route.grade %>
      <%= f.select(:discipline, [['Sport',  :sport], ['Boulder', :boulder]], selected: route.discipline)%>

      <%= f.submit %>
    <% end %>
    
  <% end %>
  <%= form_for :route, url: routes_path, method: :post do |f| %>
      <%= f.text_field :name, placeholder: 'Name' %>
      <%= f.number_field :points, placeholder: 'Points' %>
      <%= f.text_field :color, placeholder: 'Color' %>
      <%= f.text_field :grade, placeholder: 'Grade' %>
      <%= f.text_field :comp_id, value: @comp.id, type: :hidden %>
      <%= f.select(:discipline, [['Sport',  :sport], ['Boulder', :boulder]])%>

      <%= f.submit %>
  <% end %>
  </ul>

app/views/comps/index.html.erb
<% if @comps.empty? %>
  <h3>
    REST DAY TODAY: NO CURRENTLY OPEN COMPS!
  </h3>

<% else %>
  <h2>
    JOIN A COMP
  </h2>

  <%= render partial: 'compcard', locals: {comps: @comps} %>
<% end %>

<% unless @upcoming.empty? %>
  <h3>
    UPCOMING
  </h3>

  <%= render partial: 'compcard', locals: {comps: @upcoming} %>
<% end %>

<% unless @recent.empty? %>
  <h3>
    RECENT
  </h3>

  <%= render partial: 'compcard', locals: {comps: @recent} %>
<% end %>

app/views/comps/new.html.erb
<h2>
  NEW COMP
</h2>

<%= render partial: 'form' %>

app/views/comps/show.html.erb
<button class="tab" id="malesTab" onclick="renderLeadersForGender(LEADERS, 'males')">Men</button>
<button class="tab" id="femalesTab" onclick="renderLeadersForGender(LEADERS, 'females')">Women</button>
<button class="tab" id="collegesTab" onclick="renderLeadersForGender(LEADERS, 'colleges')">College</button>

<b>Bouldering Leaders</b><br>
<ul class="sheet" id="boulder">
    <li><div><b>Name:</b></div><div><b>College:</b></div><div><b>Points:</b></div></li>
</ul>

<b>Sport Climbing Leaders</b><br>
<ul class="sheet" id="sport">
    <li><div><b>Name:</b></div><div><b>College:</b></div><div><b>Points:</b></div></li>
</ul>

<b>Speed Climbing Leaders</b><br>
<ul class="sheet" id="speed">
    <li><div><b>Name:</b></div><div><b>College:</b></div><div><b>Time:</b></div></li>
</ul>