config/routes.rb
Rails.application.routes.draw do

  root controller: 'comps', action: 'index'

  resources :comps do
    member do
      get 'join'
      get 'leaders'
    end
  end

  resources :climbers do
    collection do
      put 'login'
      get 'signin'
      put 'logout'
    end
  end

  resources :routes do
    member do
      put 'sendClimb'
      put 'attemptClimb'
      put 'witnessClimb'
    end
  end

  resources :colleges

  get 'scoresheet' => 'scoresheets#index'
  put 'scoresheet/speed' => 'scoresheets#speed'
  get 'scoresheet/climbs' => 'scoresheets#climbs'
  get 'scoresheet/submit' => 'scoresheets#submit'
  get 'scoresheet/scores' => 'scoresheets#scores'

end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :climbers
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :find_college, except: [:index, :new, :create]

  def show

  end

  def index
    @colleges = College.all.order('name ASC')
  end

  def new
    @college = College.new
  end

  def create
    @college = College.new(college_params)
    if @college.save
      redirect_to colleges_path
    else 
      redirect_to colleges_path
    end
  end

  def edit

  end

  def update
    if @college.update(college_params)
    #render_data("success")
      redirect_to colleges_path
    else
      render_error("error")
    end
  end

  def destroy

  end


  private

  def find_college
    @college = College.find(params[:id])
  end

  def college_params
    params.require(:college).permit(:name)
  end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/index.html.erb
<ul>
<% @colleges.each do |c| %>
  <li class='college-card'>
  <div class='cname' id='display<%= c.id %>'><%= c.name %></div>
  <div class='cform hidden' id='form<%= c.id %>'>
    <%= form_for :college, url: college_path(c), method: :patch do |f| %>
      <%= f.text_field :name, value: c.name %>
      <%= f.submit %>
    <% end %>
  </div>


    <%= iconbutton('fa-edit c-edit', c.id) %>
    <%= iconbutton('fa-close', c.id) %>

  </li>
<% end %>
<li>
<div class='cnew hidden'>
<%= form_for :college, url: colleges_path, method: :post do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.submit %>
<% end %>
</div>
<div class='new-college'>
New
<%= iconbutton 'fa-plus' %>
</div>

</li>
</ul>

app/views/colleges/new.html.erb
<h2>
  NEW COLLEGE
</h2>


<%= form_for @college do |f| %>
  <%= render partial: 'layouts/errors', locals: {obj: @college} %>

  <h4>
    NAME
  </h4>

  <%= f.text_field(:name, class: 'input-large') %>
  <br />
  <br />
  <%= f.submit("SUBMIT", class: 'block-link') %>

<% end %>