config/routes.rb
Rails.application.routes.draw do

  root controller: 'comps', action: 'index'

  resources :comps do
    member do
      get 'join'
      get 'leaders'
    end
  end

  resources :climbers do
    collection do
      put 'login'
      get 'signin'
      put 'logout'
    end
  end

  resources :routes do
    member do
      put 'sendClimb'
      put 'attemptClimb'
      put 'witnessClimb'
    end
  end

  resources :colleges

  get 'scoresheet' => 'scoresheets#index'
  put 'scoresheet/speed' => 'scoresheets#speed'
  get 'scoresheet/climbs' => 'scoresheets#climbs'
  get 'scoresheet/submit' => 'scoresheets#submit'
  get 'scoresheet/scores' => 'scoresheets#scores'

end

app/models/scoresheet.rb
class Scoresheet < ActiveRecord::Base
  has_many :climbs
  belongs_to :comp
  belongs_to :climber
  has_many :routes, through: :climbs

  after_initialize :init

  validates :climber_id, presence: true
  validates :comp_id, presence: true
  validates :boulder_score, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :sport_score, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  BOULDERCOUNT = 5
  SPORTCOUNT = 3
  LEADERCOUNT = 3

  scope :boulder_leaders, -> { order(boulder_score: :desc).limit(LEADERCOUNT) }
  scope :sport_leaders, -> { order(sport_score: :desc).limit(LEADERCOUNT) }
  scope :speed_leaders, -> { order(speed: :asc).limit(LEADERCOUNT) }

  def init
    self.boulder_score ||= 0
    self.sport_score ||= 0
  end

  def record_speed time
    time = time.to_f
    if time == 0
      return false
    end
    if self.speed_attempt1.nil?
      self.speed_attempt1 = time
      self.speed = time
    elsif self.speed_attempt2.nil?
      self.speed_attempt2 = time
      if time < self.best_speed
        self.speed = time
      end
    else
      return false
    end
    self.save
  end

  def get_climbs
    Route.joins("LEFT JOIN climbs on routes.id = climbs.route_id AND climbs.scoresheet_id = #{self.id} AND routes.comp_id = #{self.comp.id}").select("routes.*, climbs.attempts AS attempts, climbs.sent AS sent, climbs.witness AS witness")
      .order('routes.points asc')
  end

  def update_scores
    sent = Route.joins(:climbs).where("climbs.scoresheet_id = ? AND climbs.sent = TRUE", self.id)
    sport = sent.sport.collect(&:points).sum
    boulder = sent.boulder.collect(&:points).sum
    self.sport_score = sport
    self.boulder_score = boulder
    self.save
  end

end

app/controllers/scoresheets_controller.rb
class ScoresheetsController < ApplicationController

  before_action :find_scoresheet

  def index
  end

  def scores
    render json: @scoresheet
  end

  def climbs
    render json: @scoresheet.get_climbs
  end

  def speed
    saved = @scoresheet.record_speed(params[:time])
    if saved
      render json: @scoresheet
    else
      render_error(500, "speed save failed")
    end
  end

  def submit
    session[:scoresheet] = nil
    redirect_to root_path
  end

  def find_scoresheet
    @scoresheet = current_scoresheet
    if @scoresheet.nil?
      render_error(500, "No active scoresheet")
      return
    end
  end


end

app/helpers/scoresheet_helper.rb
module ScoresheetHelper
end

app/views/scoresheets/index.html.erb
<div class='navbar'>
  <ul class='navList'>
    <li class='nav home'>
      <%= link_to @current_scoresheet.comp.location, scoresheet_path %>
    </li>
    <li class='nav'>
      <%= link_to 'Leaderboard', @current_scoresheet.comp %>
    </li>
    <li class='nav'>
      <%= link_to 'Submit', 'scoresheet/submit' %>
    </li>
  </ul>
</div>

<div class="sheet">
    <button class="tab" id="boulderTab" onclick="renderClimbs(CLIMBS, 'boulder')">Boulder</button>
    <button class="tab" id="sportTab" onclick="renderClimbs(CLIMBS, 'sport')">Sport</button>
    <button class="tab" id="speedTab" onclick="renderClimbs(CLIMBS, 'speed')">Speed</button>

    <ul class="table" id="table">
        <span id="cols"><li><div>Points</div><div>Color</div><div>Attempts</div></li><span>
    </ul>
</div>