config/routes.rb
Rails.application.routes.draw do

  root controller: 'comps', action: 'index'

  resources :comps do
    member do
      get 'join'
      get 'leaders'
    end
  end

  resources :climbers do
    collection do
      put 'login'
      get 'signin'
      put 'logout'
    end
  end

  resources :routes do
    member do
      put 'sendClimb'
      put 'attemptClimb'
      put 'witnessClimb'
    end
  end

  resources :colleges

  get 'scoresheet' => 'scoresheets#index'
  put 'scoresheet/speed' => 'scoresheets#speed'
  get 'scoresheet/climbs' => 'scoresheets#climbs'
  get 'scoresheet/submit' => 'scoresheets#submit'
  get 'scoresheet/scores' => 'scoresheets#scores'

end

app/views/layouts/_errors.html.erb
 <% if obj.errors.any? %>
    <div class='error-explanation'>
      <p>Sorry!</p>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Compclimbr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='wrapper'>
<div class='navbar'>
  <ul class='navList'>
    <li class='nav home'>
      <%= link_to icon("fa-home") + " SENDR", root_path %>
      </li>
      <% if @current_climber.nil? %>
      <li class='nav'>
      <%= link_to icon("fa-sign-in"), signin_climbers_path %>
      </li>
    <% else %>
 <li class='nav'>
        <%= link_to icon("fa-sign-out"), logout_climbers_path, method: 'put' %>
      </li>

      <li class='nav'>
      <%= link_to icon("fa-user") +" #{@current_climber.name}" , @current_climber %>
      </li>
         <% end %>
  </ul>
</div>
<div id='content'>

  <%= yield %>
</div>
</div>

</body>
</html>